version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: cooperados-app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - net
  nginx:
    image: nginx:alpine
    container_name: cooperados-web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - net
  db:
    image: mysql:8.0
    container_name: cooperados-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cooperados
      MYSQL_USER: cooper
      MYSQL_PASSWORD: secret
    ports:
      - "33060:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - net
  node:
    image: node:18-alpine
    container_name: cooperados-node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - net

volumes:
  dbdata:

networks:
  net:
    driver: bridge
